### ISSUE TITLE
UX Improvements - Central Todo List

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/crypto-code-school-inside-tezos#74]
## Major
- [x] Game onboarding
- [x] Explicit Plant Evolution
- [x] Gameplay modal after lesson completion
- [x] Remove Get Help Button
- [x] What to show on right side in chapters that have no code?
- [x] Design content for ending chapter. 
- [ ] Success modals to be shown in each chapter (ideal to show when is the next evolution stage occuring)
- [x] Editor font size - too big for small screens. 
- [ ] Show Answer isn't toggle-able to hide answer. 

## Minor UI fixes 
- [x] Tooltips for Icon based buttons (Important)
- [x] Icons to be replaced (Important)
- [x] Back button consistency across views (learning, chapters, completion, gameplay)
- [x] Reducing the top and bottom margins/padding of “Start Now” button on the landing page (Important)

Other issues: 
- [ ] Close #92 
- [ ] Close #91

**Comment by bhaskarSingh** [comment]
> Reducing the top and bottom margins/padding of “Start Now” button on the landing page (Important)

@AbhinavThukral97  is the padding/margin approriate now ? current state can be checked by going through: [cryptocodeschool](https://cryptocodeschool.in/tezos)

**Comment by AbhinavThukral97** [comment]
![image](https://user-images.githubusercontent.com/6816349/80676493-7fcc0b80-8ad4-11ea-9043-ccf16b5637d7.png)

![image](https://user-images.githubusercontent.com/6816349/80676599-befa5c80-8ad4-11ea-80d4-0b61d4a9bdaf.png)

I think we can still reduce space. The start now button is taking a lot of space (also can you reduce the size of the icon in the button, it feels a bit out of proportion). We can also reduce the spacings in footer - reducing the font-size and margins with the text, and also fixing BUIDL Lab's logo to go with the footer background

**Comment by prastut** [comment]
Stale
